import = [
  "~/.config/alacritty/themes/themes/deep_space.toml"
]

[window]
padding.x = 17
padding.y = 17
decorations = "Full"
opacity = 0.6
dynamic_padding=true
decorations_theme_variant="None"


[font]
normal.family = "FiraCode Nerd Font"
size = 16
